INSERT INTO USERS (name, email, password)
VALUES ('User', 'user@yandex.ru', '{noop}password'),
       ('Admin', 'admin@gmail.com', '{noop}admin'),
       ('Guest', 'guest@gmail.com', '{noop}guest');

INSERT INTO USER_ROLE (role, user_id)
VALUES ('USER', 1),
       ('ADMIN', 2),
       ('USER', 2);


INSERT INTO RESTAURANT (ID, NAME) VALUES (1000, 'Italiano');
INSERT INTO RESTAURANT (ID, NAME) VALUES (2000, 'Sushi');
INSERT INTO RESTAURANT (ID, NAME) VALUES (3000, 'Burger');

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (101, 1000, 'Pizza Margherita', 9.99, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (102, 1000, 'Pasta Carbonara', 11.50, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (201, 1000, 'California Roll', 8.00, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (301, 3000, 'Cheeseburger', 10.00, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (302, 3000, 'Fries', 3.50, CURRENT_DATE);
