INSERT INTO USERS (name, email, password)
VALUES ('User', 'user@yandex.ru', '{noop}password'),
       ('Admin', 'admin@gmail.com', '{noop}admin'),
       ('Guest', 'guest@gmail.com', '{noop}guest');

INSERT INTO USER_ROLE (role, user_id)
VALUES ('USER', 1),
       ('ADMIN', 2),
       ('USER', 2);


INSERT INTO RESTAURANT (ID, NAME) VALUES (1, 'Italiano');
INSERT INTO RESTAURANT (ID, NAME) VALUES (2, 'Sushi');
INSERT INTO RESTAURANT (ID, NAME) VALUES (3, 'Burger');

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (101, 1, 'Pizza Margherita', 9.99, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (102, 1, 'Pasta Carbonara', 11.50, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (201, 2, 'California Roll', 8.00, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (301, 3, 'Cheeseburger', 10.00, CURRENT_DATE);

INSERT INTO MENU_ITEM (ID, RESTAURANT_ID, NAME, PRICE, DATE)
VALUES (302, 3, 'Fries', 3.50, CURRENT_DATE);

INSERT INTO VOTE (ID, USER_ID, RESTAURANT_ID, DATE, TIME)
VALUES (1, 3, 1, CURRENT_DATE, '10:00');


ALTER TABLE restaurant ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE menu_item ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE vote ALTER COLUMN id RESTART WITH 1000;
